[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "autollmrerank"
version = "0.1.10"
description = "A modular reranking library with pluggable LLM, prompt, and parser interfaces."
authors = [{ name = "XXXXX", email = "XXXXX" }]
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
autollmrerank = ["configs/*.yaml"]
