# default_config.yaml
data:
  ir_dataset_name: msmarco-passage/trec-dl-2019/judged
  input_run: ../../runs/run.msmarco-v1-passage.bm25-trec-dl-2019.txt

model:
  model_name_or_path: Qwen/Qwen2.5-7B-Instruct
  max_length: 4096
  use_logits: false
  use_alpha: false

output:
  output_run: ../../runs/temp.txt
  save_path: ./checkpoints/model.pt

logging:
  log_dir: ./logs
