data:
  batch_size: 32
  ir_datasets_name: msmarco-passage/trec-dl-2019/judged
  input_run: runs/run.msmarco-passage.bm25-trec-dl-2019.txt

llm:
  model_name_or_path: Qwen/Qwen2.5-7B-Instruct
  temperature: 0.0
  top_p: 1.0
  backend: vllm
  max_model_len: 8196
  dtype: float16
  use_logits: false

rerank_mode: RankGPT 
use_alphabetical: false
top_k: 100 
rank_start: 0
rank_end: 100 
max_doc_length: null
context_size: 1024
window_size: 20
step_size: 10
exp: implemented
num_runs: 1
dtype: float16
variable_passages: true
include_system_message: true
system_message: "You are RankLLM, an intelligent assistant that can rank passages based on their relevancy to the query"
result_parser_name: listwise
